version: '3'
services:
  db:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
  phonebook:
    build: .
    container_name: phonebook
    ports:
     - "8081:8080"
    environment:
      OPENSHIFT_MYSQL_DB_HOST: db
      OPENSHIFT_MYSQL_DB_PORT: 3306
    depends_on:
     - db
    links:
     - db